[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = [
    "@remotion/renderer",
    "@remotion/bundler",
    "esbuild",
    "ffmpeg-static",
    "ffprobe-static"
  ]
  included_files = [
    "node_modules/ffmpeg-static/**",
    "node_modules/ffprobe-static/**"
  ]
